FROM openjdk:8u151-jdk-alpine
LABEL maintainer="Prabhneet S Arora <prabhneet.java@gmail.com>"
ENV REFRESHED_AT 2017-12-17
EXPOSE 8080
RUN mkdir /voter && cd /voter
COPY build/libs/voter-*.jar voter-service.jar 
CMD [ "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "voter/voter-service.jar" ]
